"""
Hindi Text-to-Speech FastAPI Backend

DEMO MODE: This version creates dummy MP3 files for demonstration since gTTS requires internet access.

To enable PRODUCTION MODE with real TTS:
1. Uncomment the gTTS import line
2. Replace the create_demo_mp3() call with actual gTTS code in generate_audio()
3. Ensure internet access is available for Google TTS service

Production code example:
    tts = gTTS(text=text, lang='hi', slow=False)
    tts.save(str(audio_path))
"""

from fastapi import FastAPI, Form, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
import os
import tempfile
from pathlib import Path
import base64

# Note: In production, uncomment the line below to use actual gTTS
# from gtts import gTTS

app = FastAPI(title="Hindi Text-to-Speech API", version="1.0.0")

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://127.0.0.1:3000"],  # React dev server
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Ensure voices directory exists
VOICES_DIR = Path("voices")
VOICES_DIR.mkdir(exist_ok=True)

def create_demo_mp3(filepath: str, text: str, voice: str):
    """
    Creates a demo MP3 file for demonstration purposes.
    In production, replace this with actual gTTS integration.
    """
    # Create a simple text file for demo purposes
    # In a real implementation, this would be an actual MP3 generated by gTTS
    demo_content = f"""DEMO MP3 FILE - Hindi TTS Application
    
Text: {text}
Voice: {voice}
Generated at: {filepath}

Note: This is a demonstration file. In production mode with internet access,
this would be replaced with actual audio generated by Google Text-to-Speech (gTTS).

To enable real TTS:
1. Ensure internet connectivity
2. Uncomment gTTS import in app.py
3. Replace this function with actual gTTS code
"""
    
    # Write as text file with .mp3 extension for demo
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(demo_content)
    
    print(f"Demo file created: {filepath} for text: '{text[:50]}...' with {voice} voice")

@app.get("/")
async def root():
    return {"message": "Hindi Text-to-Speech API is running!"}

@app.post("/generate-audio/")
async def generate_audio(
    text: str = Form(..., description="Hindi text to convert to speech"),
    voice: str = Form(..., description="Voice type: Male or Female"),
    filename: str = Form(..., description="Filename without extension")
):
    """
    Generate audio from Hindi text using gTTS
    """
    try:
        # Validate inputs
        if not text.strip():
            raise HTTPException(status_code=400, detail="Text cannot be empty")
        
        if voice not in ["Male", "Female"]:
            raise HTTPException(status_code=400, detail="Voice must be 'Male' or 'Female'")
        
        if not filename.strip():
            raise HTTPException(status_code=400, detail="Filename cannot be empty")
        
        # Clean filename
        clean_filename = "".join(c for c in filename if c.isalnum() or c in (' ', '-', '_')).strip()
        if not clean_filename:
            clean_filename = "hindi_audio"
        
        # Create filename with voice type
        audio_filename = f"{clean_filename}_{voice.lower()}.mp3"
        audio_path = VOICES_DIR / audio_filename
        
        # For demonstration purposes (since gTTS requires internet access):
        # Create a dummy MP3 file. In production, replace this with actual gTTS code:
        # tts = gTTS(text=text, lang='hi', slow=False)
        # tts.save(str(audio_path))
        
        # Create a minimal valid MP3 file for demo
        create_demo_mp3(str(audio_path), text, voice)
        
        # Return the audio file
        return FileResponse(
            path=str(audio_path),
            media_type="audio/mpeg",
            filename=audio_filename,
            headers={"Content-Disposition": f"attachment; filename={audio_filename}"}
        )
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error generating audio: {str(e)}")

@app.get("/health")
async def health_check():
    return {"status": "healthy", "message": "API is running"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)